name: React CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Build project
        env:
          NODE_ENV: production # Ensure this is explicitly set
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/nizar/Projects/reactBase  # Path to your application on the server
            git fetch
            git reset --hard origin/main  # Forcefully pull the latest changes
            npm install  # Install dependencies if necessary
            npm run build  # Build the project   
            # Serve the build directory
            pm2 stop reactBase  # Stop the old process
            pm2 delete reactBase  # Remove the old process
            pm2 start serve --name "reactBase" -- -s build -l 3000  # Serve the build folder on port 3000
            pm2 save
